//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xcolor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionCliente
    {
        public int ID { get; set; }
        public int idCliente { get; set; }
        public string direccion { get; set; }
        public int idProvincia { get; set; }
        public int idCanton { get; set; }
        public int idDistrito { get; set; }
        public int idTipoDireccion { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual TipoDireccion TipoDireccion { get; set; }
    }
}
