//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xcolor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosxPerfil
    {
        public int ID { get; set; }
        public int idPermiso { get; set; }
        public int idPerfil { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Permisos Permisos { get; set; }
    }
}
